services:
  mongo:
    container_name: dlpl_mongo-container
    hostname: mongo
    image: mongo:6.0 #https://hub.docker.com/_/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo"
      MONGO_INITDB_ROOT_PASSWORD: "mongo"
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped
    networks:
      - development
  redis:
    image: redis:7.0.4-alpine #https://hub.docker.com/_/redis
    container_name: dlpl_redis-container
    hostname: redis
    expose:
      - 6379
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: unless-stopped
    networks:
      - development
  dbgate:
    image: dbgate/dbgate:5.5.6-alpine # https://hub.docker.com/r/dbgate/dbgate
    container_name: dlpl_dbgate
    hostname: dbgate-webserver
    volumes:
      - dbgate-data:/root/.dbgate
    ports:
      - 3100:3000
    environment:
      CONNECTIONS: mongo,redis
      LABEL_redis: Redis
      URL_redis: redis://redis:6379
      ENGINE_redis: redis@dbgate-plugin-redis
      LABEL_mongo: MongoDB
      SERVER_mongo: mongodb://mongo:mongo@mongo:27017
      ENGINE_mongo: mongo@dbgate-plugin-mongo
    restart: unless-stopped
    networks:
      - development
networks:
  development:
volumes:
  mongodb-data:
  dbgate-data:
